import NavbarComponent from "@/components/NavbarComponent";
import "./globals.css";
import { Inter } from "next/font/google";
import SidebarComponent from "@/components/SidebarComponent";
import FooterComponent from "@/components/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarComponent />

        {/* <SidebarComponent /> */}
        <div className="layer">
          <div className="mainContent">{children}</div>
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
